name:                weight-recorder
version:             0.1.0.0
github:              "ciruzzo/weight-recorder"
license:             BSD3
author:              "Yoshihiro Tsuchiya"
maintainer:          "tsuchiya.yoshihiro@gmail.com"
copyright:           "Copyright (c) Yoshihiro Tsuchiya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ciruzzo/weight-recorder#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  weight-recorder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weight-recorder

tests:
  weight-recorder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weight-recorder
